export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";


// Modals
export const TOGGLE_TRANSACTION_PROCESSING_MODAL = "TOGGLE_TRANSACTION_PROCESSING_MODAL";
export const TOGGLE_TRANSACTION_REVIEW_MODAL = "TOGGLE_TRANSACTION_REVIEW_MODAL";
export const TOGGLE_TRANSFER_ASSET_MODAL = "TOGGLE_TRANSFER_ASSET_MODAL";



// Modal Data 
export const SET_TRANSFER_ASSET_DATA_MODAL = "SET_TRANSFER_ASSET_DATA_MODAL";